trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

# Run builds nightly to catch incompatibilities with new apispec releases
schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
      - master
  always: true

  
resources:
  repositories:
    - repository: sloria
      type: github
      endpoint: github
      name: sloria/azure-pipeline-templates
      ref: refs/heads/sloria

jobs:
- template: job--python-tox.yml@sloria
  parameters:
    toxenvs: [lint, py27, py35, py36, py37, py37-apispecdev]
    os: linux
- template: job--pypi-release.yml@sloria
  parameters:
    python: "3.7"
    distributions: "sdist bdist_wheel"
    dependsOn:
      - tox_linux
